import Navbar from "@/components/layout/navbar/Navbar";
import { Cairo } from "next/font/google";
import "@/styles/index.css";
import AppProvider from "@/context/AppContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <AppProvider>
          <Navbar /> {children}
        </AppProvider>
      </body>
    </html>
  );
}
