import { Cairo } from "next/font/google";
import "@/styles/index.css";
import AppProvider from "@/context/AppContext";
import ScrollButton from "@/components/layouts/scroll_button/ScrollButton";
import { Bounce, ToastContainer } from "react-toastify";
import QueryProvider from "@/providers/QueryProvider";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "700"],
});

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();

  const token = cookieStore.get("access_token")?.value;

  return (
    <html lang="en">
      <body className={cairo.className}>
        <QueryProvider>
          <AppProvider token={token}>
            <ScrollButton />
            <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
              transition={Bounce}
            />
            {children}
          </AppProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
